### ISSUE TITLE
Client-side memory leak

### ISSUE THREAD

**Issue by itslewiswatson** [itslewiswatson/ucd#6]
There is a critical memory leak that occurs on the client-side. Around 24 minutes into my session debugscript become flooded with ("Not enough memory"). GTA SA was using 3GB of memory. The server was fine.

Any ideas what this could be from @Risk36?

**Comment by riskzorque** [comment]
This happened to me after your addition of marker labels, though it didn't happen in the local server, not even a little. I already noticed you on that day when it happened. I'm not sure, yet.

**Comment by itslewiswatson** [comment]
Well I disabled it in d95731acefc9bf26eeb183d7e150f81788417aed, and I've been AFKing for 5 hours and 22 minutes without any memory leaks. When I was trying to diagnose and fix the leaks in UCDworld, I noticed that the client would use ~200mb and more than what it would otherwise.

I think it might have to be rewritten or we could consult someone from the MTA Team about it.

**Comment by riskzorque** [comment]
Weird how it does that, amount of markers with that element data being a string and "in range" is not that high. I guess telling MTA Team would be the best idea then.
